#!/usr/bin/env python3
"""
nuclei_templater.py — Auto-generate Nuclei YAML templates from findings.

When Claude confirms a vuln, auto-generate a reusable nuclei template
so the same pattern can be scanned across ALL future targets.

Usage:
    from nuclei_templater import NucleiTemplater
    t = NucleiTemplater()
    t.from_finding(finding_dict)
"""
import json
import os
import re
import time
from pathlib import Path


class NucleiTemplater:
    """Auto-generate Nuclei templates from confirmed findings."""

    SEVERITY_MAP = {"CRITICAL": "critical", "HIGH": "high",
                    "MEDIUM": "medium", "LOW": "low", "INFO": "info"}

    def __init__(self, output_dir: str = "nuclei-templates/custom"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def from_finding(self, finding: dict) -> str:
        """Generate nuclei template from a validated finding."""
        vuln_class = finding.get("vuln_class", finding.get("type", "unknown"))
        endpoint = finding.get("endpoint", finding.get("url", ""))
        method = finding.get("method", "GET")
        path = finding.get("path", "")
        matchers = finding.get("matchers", [])
        severity = finding.get("severity", "medium").upper()
        cve_id = finding.get("cve_id", "")
        description = finding.get("description", "")
        headers = finding.get("headers", {})
        body = finding.get("body", "")

        template_id = f"hunterAI-{vuln_class}-{int(time.time())}"

        # Build matchers
        matcher_block = self._build_matchers(matchers, finding)

        # Build request
        request_block = self._build_request(method, path, headers, body)

        template = f"""id: {template_id}

info:
  name: "{vuln_class} - Auto-generated by HunterAI"
  author: HunterAI
  severity: {self.SEVERITY_MAP.get(severity, 'medium')}
  description: |
    {description or f'Auto-detected {vuln_class} vulnerability.'}
  tags: hunterAI,{vuln_class.lower().replace(' ', '-')}
"""
        if cve_id:
            template += f"""  classification:
    cve-id: {cve_id}
  reference:
    - https://nvd.nist.gov/vuln/detail/{cve_id}
"""

        template += f"""
http:
  - method: {method}
    path:
      - "{{{{BaseURL}}}}{path or '/'}"
"""
        if headers:
            template += "    headers:\n"
            for k, v in headers.items():
                template += f'      {k}: "{v}"\n'

        if body:
            template += f'    body: "{body}"\n'

        template += f"""
    matchers-condition: and
    matchers:
{matcher_block}
"""

        # Save template
        filename = f"{template_id}.yaml"
        filepath = self.output_dir / filename
        filepath.write_text(template, encoding="utf-8")

        return str(filepath)

    def _build_matchers(self, matchers: list, finding: dict) -> str:
        """Build nuclei matcher block."""
        if matchers:
            block = ""
            for m in matchers:
                block += f'      - type: {m.get("type", "word")}\n'
                if "words" in m:
                    block += "        words:\n"
                    for w in m["words"]:
                        block += f'          - "{w}"\n'
                if "status" in m:
                    block += f'        status:\n          - {m["status"]}\n'
                if "regex" in m:
                    block += f'        regex:\n          - "{m["regex"]}"\n'
            return block

        # Auto-generate matchers based on vuln class
        vuln = finding.get("vuln_class", finding.get("type", ""))
        status = finding.get("status_code", 200)

        block = f"""      - type: status
        status:
          - {status}
"""
        if "idor" in vuln.lower():
            block += """      - type: word
        words:
          - "email"
          - "phone"
          - "address"
        condition: or
"""
        elif "xss" in vuln.lower():
            block += """      - type: word
        words:
          - "<script>"
          - "alert("
          - "onerror="
        condition: or
"""
        elif "sqli" in vuln.lower() or "sql" in vuln.lower():
            block += """      - type: regex
        regex:
          - "(?i)(error|syntax|mysql|postgresql|oracle|mssql)"
"""
        elif "ssrf" in vuln.lower():
            block += """      - type: word
        words:
          - "169.254.169.254"
          - "metadata"
          - "internal"
        condition: or
"""
        return block

    def _build_request(self, method, path, headers, body):
        return ""

    def from_cve(self, cve_id: str, product: str, version: str,
                 path: str = "/", check_header: str = "") -> str:
        """Generate template for a known CVE."""
        finding = {
            "vuln_class": "known_cve",
            "cve_id": cve_id,
            "path": path,
            "method": "GET",
            "severity": "HIGH",
            "description": f"Check for {cve_id} in {product} {version}",
            "matchers": [
                {"type": "status", "status": 200},
            ],
        }
        if check_header:
            finding["matchers"].append({
                "type": "word", "words": [f"{product}/{version}"],
            })
        return self.from_finding(finding)

    def list_templates(self) -> list:
        return [str(f) for f in self.output_dir.glob("*.yaml")]
